meta_weight: [ 0.1, 0,2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
bate: [ 1 ]
n_meta_layer: [ 5, 6, 7, 8, 9 ]
n_ui_layers: [ 5, 6, 7, 8, 9 ]
n_mm_layers: [ 2 ]
reg_weight: [ 1e-06 ]
hyper_parameters: [ "n_ui_layers", "n_mm_layers", 'meta_weight','n_meta_layer','reg_weight','modalrate' ]
