# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
INTER_RATE: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'sports.inter'
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'
field_separator: "\t"
embedding_size: 64
feat_embed_dim: 64
cf_model: lightgcn



